# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(40, 110, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Onyx")
        font.setPointSize(20)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Onyx")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Berat_Badan = QtWidgets.QLineEdit(self.centralwidget)
        self.Berat_Badan.setGeometry(QtCore.QRect(250, 130, 181, 41))
        self.Berat_Badan.setObjectName("Berat_Badan")
        self.Tinggi_Badan = QtWidgets.QLineEdit(self.centralwidget)
        self.Tinggi_Badan.setGeometry(QtCore.QRect(250, 210, 181, 41))
        self.Tinggi_Badan.setObjectName("Tinggi_Badan")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setLineWidth(2)
        self.label_3.setMidLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.Hasil_BMI = QtWidgets.QLabel(self.centralwidget)
        self.Hasil_BMI.setGeometry(QtCore.QRect(50, 370, 371, 81))
        self.Hasil_BMI.setText("")
        self.Hasil_BMI.setObjectName("Hasil_BMI")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Onyx")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.onclick)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def onclick(self):
        try:
            tinggi_cm = float(self.Tinggi_Badan.text())
            berat_kg = float(self.Berat_Badan.text())

            if tinggi_cm <= 0 or berat_kg <= 0:
                self.Hasil_BMI.setText("Masukkan angka lebih besar dari 0 untuk berat dan tinggi badan.")
                return

            tinggi_m = tinggi_cm / 100  # Konversi ke meter
            bmi = berat_kg / (tinggi_m ** 2)

            if bmi < 17.0:
                hasil = "Berat badan anda kurus kerontang."
            elif 17.0 <= bmi < 18.5:
                hasil = "Sepertinya anda kurus."
            elif 18.5 <= bmi < 25.0:
                hasil = "Anda manusia normal."
            elif 25.0 <= bmi < 27.0:
                hasil = "Anda gemuk tingkat normal."
            else:
                hasil = "Anda gemuk tingkat tinggi."

            self.Hasil_BMI.setText(f"Nilai BMI Anda: {bmi:.2f}\n{hasil}")
        except ValueError:
            self.Hasil_BMI.setText("Masukkan angka yang valid untuk berat dan tinggi badan.")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Masukan Berat Badan Anda : "))
        self.label_2.setText(_translate("MainWindow", "Masukan Tinggi Badan Anda :"))
        self.label_3.setText(_translate("MainWindow", "Kalkulator BMI"))
        self.pushButton.setText(_translate("MainWindow", "Hitung"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
